### ISSUE TITLE
[Question]  Building

### ISSUE THREAD

**Issue by BlockyTheDev** [ds58/Panilla#101]
Yes, I have buyed the plugin in SpigotMC to support the developers of this plugin. But now I want to make some minor adjustments on it and I don't get it build with the message (see at the end).

Now my questions: How are the jars from SpigotMC compiled to stop this error from happening?

> Task :panilla-craftbukkit-v1_17_R1:compileJava FAILED
C:\Users\PC4-User\Desktop\tt\Panilla\craftbukkit-v1_17_R1\src\main\java\com\ruinscraft\panilla\craftbukkit\v1_17_R1\InventoryCleaner.java:10: error: cannot access net.minecraft.nbt.NBTTagCompound
import net.minecraft.nbt.NBTTagCompound;
                        ^
  bad class file: C:\Users\PC4-User\.m2\repository\org\spigotmc\spigot\1.17-R0.1-SNAPSHOT\spigot-1.17-R0.1-SNAPSHOT.jar(net/minecraft/nbt/NBTTagCompound.class)
    class file has wrong version 60.0, should be 52.0

**Comment by BetTD** [comment]
Not sure if you're still facing this issue, but since I assume this won't be the last time anyone might face this problem (I literally just ran into the same issue), I'll just post the solution.

Compile the plugin using Java 17. You're most likely using Java 8 at the moment (you can confirm this by running ``java -version`` in a command prompt window). Try installing OpenJDK 17, it *should* overwrite your ``java`` command and let you compile the plugin.

**Comment by ds58** [comment]
Building is done with JDK 17. I admit it's really a mess with all the CraftBukkit versions which have to be installed.

**Comment by BlockyTheDev** [comment]
> Building is done with JDK 17. I admit it's really a mess with all the CraftBukkit versions which have to be installed.

But how is it then working with the 1.8.8/.../1.16.5 support? These versions are not on JDK 17?

Or is gradle in the "position" that it can set an compatibillity of java 8 to the classes build with jdk17, with the sourceCompatibility = 1.8 and targetCompatibility = 1.8? Sorry for the questsions @ds58 , I am asking you so accurate because I am working on public plugins with gradle, too and haven't found any solution to build something with support for 1.8 until 1.18 in one build process.

**Comment by ds58** [comment]
Yes, the source and target compatibility are set to 1.8, this allows the binary to be compatible with a JRE 8 runtime -- ie compatible with a MC 1.8 server running on JRE 8. This also means Panilla's code must be compliant with JDK 8. Can't use any newer Java features as they won't exist in the older server versions.

We must build with JDK 17 however, because BuildTools for newer versions of CraftBukkit generates maven artifacts that use JDK 16/17, etc. Building with JDK 8 would result in a wrong class version error.

https://github.com/ds58/Panilla/blob/master/build.gradle#L14-L15

**Comment by BlockyTheDev** [comment]
Thanks for the answers. ✅
